# Monday, May 16, 2022 

### Legend {-}

```{block, type='protip'}

#### ✨ Note{-}

***All times are in Eastern Time (Canada)***
```

```{block, type='reflect'}
#### Keynote

```

```{block, type='wp'}
#### Invited Speaker

```

```{block, type='secondary'}
#### Regular Session

```
```{block, type='gh'}
#### Social Session

```

--- 



##  Welcome Desk Open (10:30 - 12:30) {-}

## Conference Welcome and Keynote (11:00 - 12:30) {-}

```{block, type='reflect'}
#### Metaphors of Ed Tech
*Martin Weller*  
[Abstract](https://otessa.github.io/2022/keynotes-intro.html#metaphors-of-edtech)

```

## Break (12:30 - 1:00) {-}

## Parallel Session 1 - Invited Speakers (1:00 – 1:45)  {-}

### Parallel Session 1.1 {-}

```{block, type='wp'}
#### **Embracing the Middle**

*Jess Mitchell*

**Keywords:** liminal, equity, inclusion

#### Abstract 

Small, Medium, Large; Short, Medium, Long; Yes, No, Maybe; Black, White, Grey
```

### Parallel Session 1.2 {-}

```{block, type='wp'}
#### **One for All, All for One, to Support and Enable Our Learning  Societies** 

*Nadia Naffi*

***Rescheduled for 2023***

**Keywords:** Sustainable educational transformation, Learning society, Learning ecosystem, Higher education, Society 5.0

#### Abstract 

The acceleration of digitalization, of automation and of cyber-physical systems, the web3.0, the gig economy, the climate change crisis, the demographic changes, the investment in green and renewable technologies and the extended lifespans, to name only few disruptive events, are reshaping the social and work-related skills we need and the way we acquire them. When COVID-19 hit, we were reminded that we were all interconnected and that educational transformation will never happen if the stakeholders remain in their own bubbles. The pandemic accentuated the urgency to rethink the role of higher education within the learning ecosystem to answer the needs of today and tomorrow’s learners, namely those who are left behind by the systems. In this presentation I’m calling for action to break silos and incite, strengthen, and sustain partnerships between all actors to support and enable our learning societies and to ensure, together, the sustainable change we need, especially if we decide to realize the vision of Society 5.0, a people-centric society with a sustainable, inclusive socio-economic system. 
```
## Break (1:45 – 2:15) {-}

## Parallel Session 2 (2:15 – 3:45) {-}

### Parallel Session 2.1 - WILDCARD: Indigenous Language Revival & K12 Truth & Reconciliation {-}

```{block, type='secondary'}
#### 2:15-2:45 
**Elders’ Conversations: Perspectives on leveraging digital technology in language revival (Research-Oriented)**

*Melissa Bishop*
```

```{block, type='secondary'}
#### 2:45-3:45 {-}

**Truth and Reconciliation Through Inquiry-based Collaborative Learning (Practice-Oriented)**

_Deirdre Houghton (Nechako Lakes School District & University of Victoria), Gary Soles (Nechako Lakes School District & University of Victoria), Andrew Vogelsang (Nechako Lakes School District & University of Victoria), Valerie Irvine (University of Victoria)_

<!--
[Materials](https://conference.otessa.org/index.php/conference/article/view/126)
-->


**Keywords**: Truth and Reconciliation, Inquiry, Secondary school, K-12, Cross-curricular, Project-based learning, Collaboration, Co-Teaching

#### Abstract

In this session, we will share a project conducted at [school name removed for review] in the [district name removed for review], which is in Northern British Columbia, Canada. Three highschool teachers from different disciplines (Social Studies, Digital Media, and Carpentry) launched a cross-curricular inquiry-based project, focusing on truth and reconciliation,  that connected the learners in their highschool and the broader community, including knowledge holders from the local Indigenous communities. Those engaged in the project examined questions around what truth and reconciliation meant to the learners and its significance. Resulting products included a legacy wall containing individual learning represented in motifs, design of the feather using wood from around the world, and a video documentary containing interviews from school and community stakeholders. We will screen clips of videos during our session, but invite participants to pre-screen the two videos (Documentary Parts 1 and 2), which can be accessed on our YouTube playlist, where a process video and a reflection video are also available.

``` 

### Parallel Session 2.2 – Sustaining Positive Change: PSE Ethics & PSE Scholarship {-}

```{block, type='secondary'}
#### 2:15-2:45 {-}

**Surveillance in the System: Data as Critical Change in Higher Education (Research-Oriented)**

_Bonnie Stewart (University of Windsor), Samatha Szcyrek (University of Windsor)_
```

```{block, type='secondary'}
####  2:45-3:45 {-}

**Cognification in Education in Light of the Fourth Industrial Revolution (Research-Oriented)**

_Vivekanandan Kumar (Athabasca University), Mohamed Ally (Athabasca University), Avgoustos Tsinakos (International Hellenic University), Muhammad Helmi Norman (Universiti Kebangsaan Malaysia)_
```

### Parallel Session 2.3 – Transitions of Online Learning and Teaching: E-Texts / OER {-}

```{block, type='secondary'}
#### 2:15-2:45 {-}

**Investigating the effects of computer-generated contextual landmarks on short-term recall of e-texts (Research-Oriented)**

_Jon Dron, Rory McGreal, Vive Kumar, Jennifer Davies (Athabasca University)_
```

```{block, type='secondary'}
#### 2:45-3:45 {-}

**Community-Led Infrastructures for Open Access Books: A Sustainable Model and Platform (Practice-Oriented)**

_Judith Fathallah (Lancaster University), Martin Eve (University of London, Tom Grady (University of London)_
```

### Parallel Session 2.4 {-}

```{block, type='secondary'}

**Flexible approaches to learning: Bridging inclusive/exclusive spaces through open educational practice (Practice-Oriented)**

_Michelle Harrison (Thompson Rivers University)_
```

```{block, type='secondary'}

**Warp and Weft: Weaving and Open Dissertation (Practice-Oriented)**

_Helen Dewaard (Lakehead University & University of British Columbia), Leo Havemann (University College London), Verena Roberts (University of Calgary & Thompson Rivers University)_
```

```{block, type='secondary'}

**Incorporating Open Educational Pedagogies and Co-mentorship Practices in Graduate Education (Research-Oriented)** 

_Cindy Ives (Athabasca University)_

<!--
[Materials](https://conference.otessa.org/index.php/conference/article/view/101)
-->

**Keywords:** open educational pedagogy, collaborative autoethnography, graduate students, co-mentorship

#### Abstract

Our collaborative autoethnographic study (CAE) explores our use of principles of open educational pedagogy (OEP) and co-mentorship to enhance graduate teaching and learning. Working within an open, online university, we are investigating the nature and extent to which we use OEP and co-mentorship, and exploring the outcomes for ourselves and our students. We seek to reduce hierarchical relationships, prioritizing student-centred practices. We aim to improve ourselves as open, flexible distance educators and to support successful student learning and research. Consistent with CAE, we are collecting self-reflective and dialogic data, and artefacts from our co-mentorship and open educational practices. As participants in this study, we are experiencing the power of CAE as a research method that moves us beyond traditional discourse leading to personal and professional growth. We anticipate that our research findings will help position our graduates and ourselves as creative thinkers, learners, and contributors in the 21st century during these times of critical change.


```

```{block, type='secondary'}

**Critical reflection: How can open reflexive frameworks redefine academic practices? (Practice-Oriented)**

_Helen DeWaard (Lakehead University & University of British Columbia), Shauna Burnie (Lakehead University)_
```

### Parallel Session 2.5 {-}

```{block, type='secondary'}
#### 2:15-2:45 – Sustaining Positive Change – PSE Open {-}

**Open educational practice and research resources created by students, for students (Practice-Oriented)**

_Marie Bartlett & Students (Thompson Rivers University)_

<!--
[Materials](https://conference.otessa.org/index.php/conference/article/view/120)
-->


**Keywords**: Undergraduate Research, Students, Open Pedagogical Practice, WordPress, Research Resources

#### Abstract

CURN (Canadian Undergraduate Research Network) is an emerging community supported by the offices of Research and Graduate Studies and Open Learning at Thompson Rivers University (TRU), which is located in Secwepemcúl̓ecw on the unceded land of the Secwépemc peoples, on the interior plateau of British Columbia.

 For a number of years, groups of TRU students have been building a CURN website as part of their undergraduate research ambassador roles, adding to each other’s work every semester: curn.trubox.ca/. 

Since the start of the initiative, the objective has been to create an open resource that would get students interested and engaged in undergraduate research.

Designed as an open pedagogy project, student research ambassadors were given the autonomy to choose the format and the structure of the resource, decide which topics to include, what they wanted to learn from the project, and how to organize their groups and creative efforts. 

```

```{block, type='secondary'}
#### 2:45-3:45: – Transitions of Online Learning and Teaching – PSE Online {-}

**Building digital fluency skills during the rapid transition to online and hybrid teaching through open access with the Ontario Extend program (Practice-Oriented)**

_Alissa Bigelow (eCampusOntario)_

<!--
[Materials](https://conference.otessa.org/index.php/conference/article/view/117)
-->



**Keywords**: online, transitions, teaching and learning, Ontario Extend


#### Abstract

At a time of unprecedented change within the educational system due to the COVID-19 global pandemic, the Ontario Extend professional learning program provides a platform for community, collaboration, and digital fluency skill development amongst postsecondary educators across the province of Ontario. A key driver for the Ontario Extend program is to provide educators with the ability to leverage diverse educational technology tools to create a more accessible learning environment for students in online and hybrid learning environments. 

The program framework builds upon “The 21st Century Educator” model (Bates, 2016), which encompasses the knowledge, skills, and attitudes identified as the foundational skills required to “thrive (and not just survive) in a digital world” (Coldwell-Nelson, 2018; Martin & Grudziecki, 2006). Educators are encouraged to engage with six online modules and reflect upon specific elements of their teaching practice. Each of the six modules promotes a learning journey focused on a combination of foundational upskilling and reskilling, with digital badges awarded upon the completion of each module. Once an educator has completed   all six modules, they are awarded the Empowered Educator micro-credential and join the growing community of Extend educators. This session will provide an overview of the program and scaling efforts to date, with time for questions.

```

## Break  (3:45 – 4:00) {-}

## Social Session (4:00 – 4:30) {-}

```{block, type='gh'}
#### Gurdeep Pandher of the Yukon {-}

**Bhangra dance class**
```

## Parallel Session 3 (4:30 – 5:30) {-}


### Parallel Session 3.1 – Sustaining Positive Change: K12, GreenTech {-}

```{block, type='secondary'}

**Improving environmental sustainability by using public school systems as centers of green energy production and conservation: Approaches to offsetting the cost of increased technology use and associated pollution (Practice-Oriented)**

_Scott Warren, Scott Moran, Kristen McGuffin (University of North Texas)_
```


### Parallel Session 3.2 – Sustaining Positive Change – PSE Open {-}

```{block, type='secondary'}

**Sustaining Complexity: Why Higher Education Should Avoid TechnoSolutionism (Practice-Oriented)**

_Jim Luke (Lansing Community College), Bonnie Stewart (University of Windsor)_
```


### Parallel Session 3.3 – Addressing the New Inequities: Critical EdTech {-}

```{block, type='secondary'}

**Rejecting the ready-made future: Reimagining technologies from and for the classroom (Research-Oriented)**

_Esteban Morales, Rachel Horst (University of British Columbia)_
```


### Parallel Session 3.4 – Addressing the New Inequities: Open {-}

```{block, type='secondary'}

**Open Educational Practices (OEP): Critical Policy Analysis in the Canadian Post-Secondary Education Context (Research-Oriented)**

_Mara Bordignon (University of Western Ontario)_
```

### Parallel Session 3.5 – Transitions of Online Learning and Teaching – Online & Society {-}

```{block, type='secondary'}

**Online or Remote Learning and Mental Health (Research-Oriented)**

_Stephanie Moore (University of New Mexico), Michael Barbour (Touro University California), George Veletsianos (Royal Roads University)_

<!--
[Materials](https://conference.otessa.org/index.php/conference/article/view/114)
-->

**Keywords**: online learning, remote learning, mental health

#### Abstract

While there has been a great deal of debate over the impact of online and remote learning on mental health and well-being, there has been no systematic syntheses or reviews of the research on this particular issue. In this session, we will present a review of research on mental health / well-being and online or remote learning. Our preliminary analyses suggest that little scholarship existed prior to 2020 and that most of these studies have been conducted during the COVID-19 pandemic. We report three findings: (a) it’s very difficult, if not impossible, to control for pandemic effects in the data, (b) studies present a very mixed picture, with variability around how mental health and well-being are measured and how / whether any causal inferences are made in relation to online and remote learning, and (c) results across these studies are extremely mixed. Based on this study, we suggest that researchers, policymakers, practitioners, and administrators exercise extreme caution around making generalizable assertions with respect to the impacts of online/remote learning and mental health.

```

## Break (5:30 - 6:00) {-}

## Parallel Session 4 (6:00 - 6:45) {-}

Invited Speakers

### Parallel Session 4.1 {-}

```{block, type='reflect'}
#### Land-use Metaphor in Scholarly Communication: A Brief Inventory and Inspection {-}

_AJ Boston_

**Keywords**: scholarly communication, metaphor, analogy, open access

#### Abstract

Practitioners in information-centered fields regularly use metaphors in the professional literature and in everyday use. Many of these are based on land use or a general understanding of the natural sciences, and sometimes (but not always) relate to a broader metaphorical concept of information ecology or information ecosystem. Discourse in fields like scholarly communication is no exception. What I recommend in this presentation is that we begin to take inventory of our earthly metaphors in scholarly communication. Then, through a deliberate inspection of our metaphorical concepts, we can check whether the assumptions each implies are consistent with our values and do not lead us to draw false, misleading, or premature conclusions. In recognizing the usefulness and effect of metaphors, we should seek to replace old ones when they cease to bear wise fruit. 
```

### Parallel Session 4.2 {-}

```{block, type='reflect'}
#### Critical Change in Online Education - What We Can Learn (And Not Learn) From COVID as a Context {-}

_Matt Bower_

**Keywords:** Online Learning, COVID-19, Technology-Mediated Learning Theory, Comprehensive Evaluation of the Use of Technology in Education

#### Abstract 

The COVID-19 pandemic prompted the rapid transformation of education worldwide, catapulting technology in some people’s eyes from being the villain of education to the hero. As international education returns to some degree of normalcy, what can we really learn from the COVID-19 experience? This presentation using Technology Mediated Learning Theory and the Comprehensive Evaluation and Use of Technology In Education framework to identify what we can, and cannot learn, based on the argument that the COVID-19 pandemic has been, and can only ever be, an educational context. Identifying the attributes of the COVID-19 context, and how those attributes have shaped education, can then provide insights that may in turn be transferred to other times, places, and people. The increased role of parents in the education of children is taken as a case in point, with data revealing how the design of online learning should be changed to account for parental knowledge, responsibilities, perspectives and preferences. Implications for the design and study of online learning are discussed.
```

## Discussion/Networking Pods (6:45 – 7:00) {-}

...or until the end of your conversation!
