# Wedesday, May 18, 2022 
### Legend {-}

```{block, type='protip'}

#### ✨ Note{-}

***All times are in Eastern Time (Canada)***
```

```{block, type='reflect'}
#### Keynote

```

```{block, type='wp'}
#### Invited Speaker

```

```{block, type='secondary'}
#### Regular Session

```
```{block, type='gh'}
#### Social Session

```

```{block, type='protip'}

#### ✨ Note{-}

***All times are in Eastern Time (Canada)***
```
--- 



##  Welcome Desk Open (10:30 - 12:30) {-}


## Conference Updates & Keynote (11:00 - 12:30) {-}

```{block, type='reflect'}
#### Outside-In: Openness as Subversion
*Maha Bali, American University in Cairo*
```



## Break (12:30 - 1:00) {-}

## Parallel Session 9 - Invited Speakers (1:00 – 1:45){-}


### Parallel Session 9.1 {-}

```{block, type='wp'}
#### Embracing Feminist Pedagogies in Learning Design

*Enilda Romero-Hall, University of Tampa*

**Keywords:** Critical Change, Feminist Pedagogy, Intersectional Feminism, Learning Design

#### Abstract 

I consider myself an intersectional feminist. Intersectional feminism considers identities to be made up of multiple social dimensions, including gender, race, sexuality, and class (Crenshaw, 1989). Because of my intersectional feminist leanings, as an academic, instructor, and learning designer, I have adopted a philosophy of feminist pedagogy. According to Shrewsbury (1987), feminist pedagogy is a philosophy of teaching/learning processes that guides our choice of classroom practices in which a community of learners is empowered to act responsibly toward each other and toward the subject matter. Feminist pedagogy also encourages us to apply what we learn to social action. For learning design practitioners and instructors, incorporating the principles of feminist pedagogy stimulates the design and development of more equitable, inclusive and transformative learning experiences. The discourse related to feminist pedagogy in the field of learning design aims to move the field toward "universal" design that considers the needs of all learners while promoting agency, equity, empowerment, and social justice.
```

### Parallel Session 9.2 {-}

```{block, type='wp'}
#### Using Wikimedia as a Teaching Tool: How Wikidata can support Indigenous and low resource languages on the internet

*Sadik Shahadu*

**Keywords:** Wikidata, Lexicography, Lexemes, Languages, Wikimedia

#### Abstract

Since Wikidata's inception in 2012, the multilingual knowledge base was primarily focused on concepts: Q-items are related to a thing or idea, not the word that describes it. As of 2018, Wikidata also stores a new type of data: words, phrases and sentences, in many languages, described in many languages. This information is stored in new types of entities, called Lexemes (L), Forms (F), and Senses (S). 

This presentation will focus on how you can use Wikimedia as a teaching tool, the lexicographic data of Wikidata: from word records, to lexemes and beyond.
```



## Break (1:45 – 2:15) {-}


## Parallel Session 10 (2:15 – 3:45) {-}


### Parallel Session 10.1 – Transitions of Online Learning and Teaching {-}

```{block, type='secondary'}
#### 2:15-2:45 – K12

**Flipped Learning in Grade 7 and 9 Mathematics (Research-Oriented)**

*Barb Brown, Nadia Delanoy, Mark Webster (University of Calgary)*
```

```{block, type='secondary'}
#### 2:45-3:15 – K12

**Using Teacher Presence to Engage Online Learners (Practice-Oriented)**

*Leanne Huston,* *Rochelle Smith, Rhyanon Logan-Goyette (Langley School District & University of Victoria)*

<!--
[Materials](https://conference.otessa.org/index.php/conference/article/view/132)

-->

**Keywords**: engagement, asynchronous online learning, blended learning, hybrid learning, social constructivism, community of inquiry, teacher presence

#### Abstract

Consistently, teachers and researchers have questioned how to engage students who are working in asynchronous online environments. Within our context, we noticed a similar trend: student disengagement in asynchronous activities. The purpose of this presentation is to support teachers in evolving online learning environments as it is not a simple matter of digitizing existing content and placing it online. Pedagogy for online learning includes deliberate planning and implementation of teacher presence, one key component for a successful transition. We have created a resource which outlines strategies to increase teacher presence in online learning environments. Our hope is that educators new to teaching online will be able to engage students asynchronously using these strategies. 
```

```{block, type='secondary'}
#### 3:15-3:45 – K12, PSE, Society

**Implementation of Education Technology in Canada: A Comparison with Korea, Finland and the EU (Research-Oriented)**

*Keith Rispin (West Vancouver School District & University of Victoria), Valerie Irvine (University of Victoria)*

<!--
[Materials](https://conference.otessa.org/index.php/conference/article/view/142)

-->
**Keywords:** technology adoption, technology implementation, educational change, learner equity, government planning, access to education

#### Abstract

In this session, we look at how education technology in Canada is distributed to K-12 students and ask whether or not it can be done in a more effective, equitable, and cost-efficient manner. It is recognized that inequity in education already exists across the country, which has been tolerated pre-pandemic, but these inequities have been exacerbated as a result of the pandemic (Stewart, 2020). Our geographical expanse, combined with the decentralized manner in which education in Canada is delivered, creates significant challenges. Education is also a provincial mandate as per the constitution (Government of Canada, 2021). In this session, we will review federal strategies for technology planning in different countries around the world (e.g., Korea, Finland, the European Union, etc.). After providing an environmental scan of these national strategic plans worldwide, we will provide recommendations for national leadership and policy development.
```


## Parallel Session 10.2 – Transitions of Online Learning and Teaching: PSE Online {-}

```{block, type='secondary'}
#### 2:15-2:45
**Taking Experiential Learning Online During COVID-19 (Research-Oriented)**

*Theodora Kapoyannis, Astrid Kendrick, Patricia Danyluk (University of Calgary)*
```

```{block, type='secondary'}
#### 2:45-3:45

**What we do today will change what happens tomorrow – Exploring university teaching during a pandemic to derive recommendations for post-pandemic times (Research-Oriented)**

*Joerdis Weilandt, Sandra Dixon, Richelle Marynowski, Lorraine Beaudin, Rumi Graham, Stavroula Malla, Angeliki Pantazi (University of Lethbridge)*
```

### Parallel Session 10.3 – Addressing the New Inequities: PSE {-}

```{block, type='secondary'}
#### 2:15-2:45

**Co-designing OER with Learners: A Replacement to Traditional College Level Assessments (Practice-Oriented)**

*Kimberlee Carter, Maria Camila Redondo Morant (Conestoga College)*

<!--
[Materials](https://conference.otessa.org/index.php/conference/article/view/110)

-->

**Keywords**: Open, OER, Open Educational Resources, Co-Construction with Learners, Co-design with Learners

#### Abstract

Academic integrity issues in higher education have been reported as increasing as the pandemic and need to learn remotely continues. The use of homework sites like Chegg, that provide learners with answers to tests and assignments increased significantly through 2019 and 2020 (Walsh et al., 2021). Open advocates have been espousing the benefits of open educational resource assignments co-constructed with learners and published in the open prior to the pandemic. These have largely been writing assignments taking the form of blogs with a focus on teaching practices. An example of this phenomenon is the Open Learner Patchbook where learners write blog posts to share in the open (Open Education Global, 2019). A faculty involved in two projects that co-designed Open Education Resources (OER) with learners was curious to know what processes learned could be applied to co-designing OER assignments in their own teaching practice as an alternative to traditional assessments where answers can be found on homework sites. Easton et al. (2019) propose that original assignments encourage learners to complete their own work. This presentation focuses on what was learned in the co-design process with learners and what can be applied to teaching practices in college diploma and certificate courses.

```


```{block, type='secondary'}
#### 2:45-3:45
**A Critical Examination of Learner-Educator Co-Creation Within a Course (Practice-Oriented)**

*Laura Killam (Queens University), Jess Mitchell (Ontario College of Art and Design University)*

<!--
[Materials](https://conference.otessa.org/index.php/conference/article/view/103)

-->


**Keywords**: Co-creation, Open Pedagogy, Co-design

#### Abstract

Co-creation is an open practice where learners participate in decision-making about aspects of course design, which in our context has included designing assessments and/or determining grades. Co-creation may also include other aspects of course design such as content curation and course planning. Engaging a whole class of learners in co-creation may liberate learners to think critically and develop their evaluative judgment because agency, reflection, and authenticity are embedded in learner-educator interactions. These cognitive skills are essential for graduates to challenge oppression and inequity in their own careers, which has a cascading impact on society. Involving students in decision making also improves learner motivation and engagement in learning. We have witnessed tremendous growth among students through co-creation but have also faced barriers to and criticism of its use. For example, challenges include fostering trusting relationships in large classes, promoting inclusion of diverse voices, and balancing workload. In this discussion, we invite multidisciplinary co-creators to explore strategies for lasting change. We hope to discuss co-creation benefits, challenges, and potential solutions to these challenges. Even though co-creation is a unique experience for each group, ongoing discussion of how to deal with potential barriers may increase our collective readiness to empower future learners.

```

### Parallel Session 10.4 {-}

```{block, type='secondary'}
#### 2:15-2:45 – Wildcard: Microlearning/Society

**The use of design-based research to design and evaluate an online microlearning intervention aiming to interrupt COVID-19 vaccine misinformation (Research-Oriented)**

*George Veletsianos (Royal Roads University), Shandell Houlden (Royal Roads University), Jaigris Hodson (Royal Roads University), Darren Reid (University College London), Christiani Thompson (University of Saskatchewan)*

**Keywords:** design-based research, learning intervention, COVID-19 misinformation, learning design, iterative design

#### Abstract 

In this presentation, we report on a design-based research effort to develop educational interventions intended to interrupt the flow of COVID-19 vaccine misinformation. Funded by a grant from the Canadian Institutes for Health Research in February 2020, one aspect of this two-year research project aimed at designing, developing, and evaluating COVID-19 microlearning interventions. By showcasing two iterations of our learning designs, we hope to inform other researchers and practitioners on how we used design-based research to address a societal problem of concern. Specifically, during our session we will (a) describe the principles that we developed to guide the development of the first iteration, (b) present our evaluation of the first iteration, and (c) explain how this evaluation informed the design and development of the second iteration of our learning design.
```

```{block, type='secondary'}
#### 2:45-3:15– Transitions of Online Learning and Teaching: PSE

**Méthodes d'évaluation et technologies : vers des activités authentiques, dans un processus itératif en soutien aux apprentissages (Practice-Oriented)**

*[Géraldine Heilporn](https://orcid.org/0000-0002-7951-4420) (Université Laval), Audrey Raynault (Université Laval), Alice Mascarenhas (Université de Sherbrooke), Constance Denis (Université de Sherbrooke)*

<!--
[Materials](https://conference.otessa.org/index.php/conference/article/view/115)

-->

**Keywords**: enseignement supérieur, évaluation, authenticité, activités d'apprentissage, soutien aux apprentissages

#### Abstract

Dans cette communication, nous présenterons diverses façons permettant de diversifier les méthodes d'évaluation avec les technologies, ce qui a pour effet de renforcer l'authenticité et le développement des compétences d'apprentissage et de littératie du 21e siècle. Les auteurs expliqueront également comment le fait de proposer plusieurs méthodes aux étudiants pour une même évaluation peut contribuer à répondre à leurs différents besoins et préférences sans augmenter la charge de travail des enseignants. En outre, les auteurs discuteront de la manière dont la diversification des méthodes d'évaluation grâce aux technologies entraîne souvent une transformation des modalités d'évaluation vers des processus continus ou itératifs comprenant des rétroactions multiples de la part des personnes enseignantes, en soutien aux apprentissages des étudiants.


```

```{block, type='secondary'}
#### 2:45-3:15 – Transitions of Online Learning and Teaching: PSE

**Quels nouveaux modèles d’affaires pour supporter les communautés de pratique en éducation? (Practice-Oriented)**

*Robert Grégoire, Jacques Cool, Olivier Alfieri (Réseau d'enseignement francophone à distance)*

<!--
[Materials](https://conference.otessa.org/index.php/conference/article/view/141)

-->

**Keywords**: Français

#### Abstract

With the advent of the so-called 21st century skills which involve information and communication technology, the educational sphere has entered a significant turmoil period. Like so many other domains in which established practices have been upended by Internet-distributed innovative platforms, the traditional actors in education are presented with a multiplicity of potential solutions while their own viability is often questioned.

Like established teaching institutions, public and private educational organizations face this new reality, particularly in the distance learning domain where the COVID-19 pandemic has exponentially accelerated those transformations. Our not-for-profit distance learning organization, francophone and pan-canadian in nature, has therefore launched a review of its business model seeking to explore four main topics: the organization and benefits ot communities of practice, emerging accreditation alternatives, the continuums of the freemium - premium model, and the intangible benefits of membership.

Four online panels hosted by two industry experts and their guests will explore the main issues around those themes. Interviews with organizations similar in nature will document various membership models and fee structure. This presentation will summarize the tendancies and reflective thinking after three of our online panel series.

```

### Parallel Session 10.5 {-}

```{block, type='secondary'}
#### 2:15-2:45 – Sustaining Positive Change – PSE Online

**Orlando: Broadening the Conversation on Women’s Writing Through A Scholarly Podcast (Practice-Oriented)**

*Christie Hurrell, Karen Bourrier, Kathryn Holland, [Jessica J Khuu](https://orcid.org/0000-0002-8699-141X) (University of Calgary)*

<!--
[Materials](https://conference.otessa.org/index.php/conference/article/view/134)

-->

**Keywords**: scholarly podcast, women's writing

#### Abstract

Orlando: A Podcast on Women’s Writing focuses on the history of women’s writing from medieval times to the present, with a particular interest in the material conditions that enable women’s writing. Taking cues from the bespoke semantic markup of the digital textbase for which it is named, Orlando: A History of Women’s Writing from the Beginnings to the Present, the podcast stimulates discussion about the conditions of possibility for women’s writing and the goals of feminist literary history. 

Building on the work of McMenemy (2018), Copeland and MacGregor (2020) and others, both the form and the content of the podcast allow the Orlando team to expand, open, and challenge traditional conceptions of scholarly knowledge, and how this knowledge is communicated. By adopting conventions such as peer review and digital archiving, the podcast asserts itself as a legitimate form of scholarship and as a potential Open Educational Resource; at the same time, its conversational and accessible style challenges norms of publishing, teaching, and learning. 

In this presentation, the Orlando team will share lessons learned from this technology-enabled, open project and how they see it contributing to a more equitable, diverse and democratic discussion of women writers and women’s writing, broadly construed.
```

```{block, type='secondary'}
#### 2:45-3:45 – Addressing the New Inequities

**A(nother) Guide for Resisting EdTech: The Case Against (or For?) Course Hero (Practice-Oriented)**

*Brenna Clarke Gray (Thompson Rivers University)*

<!--
[Materials](https://conference.otessa.org/index.php/conference/article/view/122)

-->

**Keywords**: educational technology, critical digital pedagogy, open processes, modelling processes

#### Abstract

Using Sean Michael Morris and Jesse Stommel’s landmark essay “A Guide for Resisting EdTech: The Case Against Turnitin.” as its foil, this presentation asks participants to apply the same kinds of critiques applied effectively to Turnitin in that piece to Course Hero as we evaluate its claims against the benchmarks of ethical educational technologies. This experiment in collective meaning-making provides a model for critiquing tools that have been carefully marketed but not well-studied by academics, offering a “way in” to these discussions that is rooted in the practical and factual, and not so profoundly shaped by personalities of influence.


```

## Break 3:45 – 4:00 {-}

## Social Session (4:00 – 4:30) {-}

```{block, type='gh'}
#### Kendra Coupland

**Mindfulness Session**
```

## Parallel Session 11 (4:30 – 5:30) {-}



### Parallel Session 11.1 – Transitions of Online Learning and Teaching: PSE Open {-}

```{block, type='secondary'}
#### Multi-Section Open Course Design: Design and Implications for Faculty, Sessional Instructors, and Learners (Practice-Oriented)

*Valerie Irvine, Michael Paskevicius, [Colin Madland](https://orcid.org/0000-0002-1761-1903), [Rich McCue](https://orcid.org/0000-0003-3503-5935), [Verena Roberts](https://orcid.org/0000-0003-3336-7805) (University of Victoria)*

<!--
[Materials](https://conference.otessa.org/index.php/conference/article/view/148)

-->

**Keywords**: open education, co-teaching, course design, instructional design, open educational resources, OER, intellectual property

#### Abstract

As open course designs are being implemented in regular post-secondary credit courses (beyond the massive open online course), new issues and processes need to be considered that are fundamentally different from courses offered within the traditional learning management system. In this session, we will review our approach to multi-section open course design and share our experiences working through emergent issues, such as content placement, intellectual property and attribution, etc. We will provide insights and recommendations for institutional leadership and administration, faculty area advisors, technical support staff, and sessional instructors.


```

```{block, type='secondary'}
#### Parallel Session 11.2 – Transitions of Online Learning and Teaching: K12 Online

**Nonverbal Communication (NVC) and teacher presence in collaborative online learning in primary school (Research-Oriented)**

*Ayşegül Liman Kaban (Bahcesehir University)*

**Keywords:** online learning, nonverbal communication, teaching presence, cognitive presence, interaction

#### Abstract 

Communication process requires a powerful combination of verbal and nonverbal processes that is one of the abilities that every teacher needs to master. In communication, the estimation of sixty-five to seventy percent of the message is received by nonverbal and only thirty to thirty-five percent by verbal communication. This research seeks to analyze the effect of nonverbal communication by primary teachers on the motivation and presence of students in a collaborative online learning environment. The information was gathered by questionnaires and interviews from both instructors and learners. Qualitative research methods were used in this study. The results showed that Nonverbal Communication can be an essential source of inspiration and attention for the learning process of students and a medium to attract their attention. Relying on the research outcomes that show the important role of Nonverbal Communication (NVC) in the teaching and learning process teachers by using the appropriate NVC types, eventually, play a critical role during online collaborative teaching which can affect students’ motivation and higher collaborative learning participation. To accurately convey learning content to students, teachers will have to improve and expand positive interactions.
```

```{block, type='secondary'}
#### Integration of Technology with UDL and RTI in Inclusive Classrooms (Research-Oriented)

*Diane Montgomery (University of Prince Edward Island)*

**Keywords:** inclusion, UDL, RTI, screening, interventions, assessments, technology

#### Abstract 

The transition to inclusive classrooms in Ontario meant classroom environments had to adapt to the needs of students instead of students being expected to adapt to a standardized curriculum (Parekh, 2018). Although challenges existed in the implementation of this student centered approach, some teachers addressed these obstacles through the use of technology, Universal Design for Learning (UDL) and the Response to Intervention (RTI) frameworks.

This paper combined two studies which included both teachers’ and students’ perspectives of inclusive classrooms. The primary study examined the instructional practices of eight elementary school teachers who experienced successful transitions to inclusion in bricks and mortar and virtual classrooms. The second study explored the experiences of students with and without disabilities who participated in virtual learning during the COVID-19 pandemic.

Through online interviews and classroom observations, the teachers demonstrated how technology could increase student engagement, differentiate instruction, and provide students with alternative instruction and assessment methods. However, inconsistencies were revealed in screening approaches to identify the needs of students and monitor students’ progress. The students engaged in multiple options of learning with some experiences more positive than others.

The paper concludes with a summary of technology-based inclusive practices shared by teachers and students.
```

```{block, type='secondary'}
#### Creating a Socially Inclusive Learning Environment Through Mobile Technologies for Students with Autism Spectrum Disorders (Research-Oriented)

*Rahim Pira (University of Calgary)*
```

### Parallel Session 11.3 – Transitions of Online Learning and Teaching – PSE Assessment {-}

```{block, type='secondary'}
#### No Need to Cheat, Every Reason to Succeed: The Benefits of Alternative, Authentic Assessments in Online English Literature Courses (Research-Oriented)

*Shannon Lodoen, University of Waterloo*
```

### Parallel Session 11.4 – Sustaining Positive Change - Ethics {-}

```{block, type='secondary'}
#### Applying Trauma-informed Design to Online and Face-to-Face Teaching and Learning (Research-Oriented)

*Suzanne Reinhardt (Simon Fraser University)*

**Keywords**: online teaching and learning, trauma-informed practice, trauma-informed, care-centered pedagogy

<!--
[Materials](https://conference.otessa.org/index.php/conference/article/view/51)

-->
#### Abstract

Schools and educational systems have as their express purpose to provide support for students throughout their learning, but they also have the power to harm. It goes without saying that no student should be harmed in the pursuit of their education. A growing area of research has begun to look at how trauma and retraumatization affect learning in tertiary education in a face-to-face modality. Fewer studies have explored trauma, and its effects, in online classes. This presentation describes a study that uses a constructivist grounded theory approach to examine how college instructors think about and design trauma-informed practices in both their online and face-to-face classes. Using dimensional analysis, the core dimension that emerged from the data was Creating a Learning Environment of Care. A model for the process of Creating a Learning Environment of Care is provided along with a model for Creating a Learning environment of Care online. Theoretical propositions and practical applications are provided based on the data from this research.

```

### Parallel Session 11.5 – Transitions of Online Learning and Teaching - PSE {-}

```{block, type='secondary'}
#### The SAMR Model as a Framework for Scaffolding Online Chat (Research-Oriented)

*Janine Aldous Arantes*

**Keywords:** SAMR, technology-enhanced learning, WhatsApp, online learning community

#### Abstract 

With its increasing reach, accessibility, and frequency of use, WhatsApp can shape the way educators and students share content and communicate in higher education. The purpose of this paper is to report on an Online Learning Community (OLC) using WhatsApp that explored the ‘Implications and Impacts' component of the Australian Digital Technologies Curriculum with seven pre-service teachers (PST). Through analysis of online chats and thematic analysis, the paper demonstrates the potential use of Puentedura’s (2014) Substitution, Augmentation, Modification and Redefinition (SAMR) model in both online learning communities and as a research method via WhatsApp. This paper reports on an example of the findings of the Substitution prompt, to support the discussion and demonstration. Unique contributions to the discussion, include the interpretive and critical approaches discussed in the paper, in terms of research methods and a guided example of using the SAMR model in a research context. The paper may be of value to both researchers who are interested in a scaffolded means to engage with participants through an online learning community, as well as teachers using technology in educational contexts.
```

## Break (5:30 – 6:00) {-}



## Parallel Session 12 - Invited Speakers (6:00 – 6:45) {-}

### Parallel Session 12.1 {-}

```{block, type='wp'}
#### Online Learning and the Disruption of Teaching and Learning

*Tony Bates*, Chang School of Continuing Education (Ryerson University) and Contact North*

**Keywords**: Covid-19, online learning, future skills, digital learning, best practices

#### Abstract

For nearly 30 years, online learning has been a growing, yet minor, part of higher education. Covid-19 and the development of synchronous video have changed this. Online learning and especially blended learning will become increasingly important, both for economic and pedagogical reasons. But we must learn from the past to ensure the quality of our future use of digital technologies. This presentation will address (a) what we have learned about successful e-learning design (b) how teaching and learning must change to meet the needs of 21st century learners and (c) the critical role that digital technologies will play in this transition.
```

### Parallel Session 12.2 {-}

```{block, type='wp'}
#### Indigenous Representation in the Academy and Beyond

*Lyn Trudeau, Brock University*

**Keywords:** representation visual reconciliation Anishinaabe storytelling 

#### Abstract 

Indigenous representation in academia has implications that extend beyond educational institutions, and must be synonymous with poor/non-representation with respect to the Indigenous population. Visual components in academic areas that are meant to reflect the history, present and future of Aboriginal people will be expressed from an Anishinaabe perspective. In addition, the importance of personal and collective storytelling and truth will be emphasized.
```



## Discussion/Networking Pods (6:45 – 7:00) {-}

...or till end of convo
