# Thursday, May 19, 2022 
### Legend {-}

```{block, type='protip'}

#### ✨ Note{-}

***All times are in Eastern Time (Canada)***
```

```{block, type='reflect'}
#### Keynote

```

```{block, type='wp'}
#### Invited Speaker

```

```{block, type='secondary'}
#### Regular Session

```
```{block, type='gh'}
#### Social Session

```

--- 



##  Welcome Desk Open (10:30 - 12:30) {-}


## Conference Updates & Keynote (11:00 - 12:30) {-}

```{block, type='reflect'}
#### Things Unsaid: Exploring the Margins and Limits of Open

*Brenna Clarke Gray, Thompson Rivers University*
```



## Break (12:30 - 1:00) {-}





## Parallel Session 13 - Invited Speakers (1:00 – 1:45) {-}


### Parallel Session 13.1 {-}

```{block, type='wp'}
#### Digital Inequalities in Education by Design

*Simon Collin, Université du Québec à Montréal*

**Keywords:** digital inequalities, design, use


#### Abstract 

Digital inequalities in education have primarily been studied in terms of disparate technological access, uses, and skills embedded in academic and social inequalities (Brotcorne, 2022). However, it is possible to think that digital inequalities are configured upstream from the use of technologies by educational actors. From this systemic perspective, inequalities of use represent the culmination of a process of configuration of digital inequalities that begins with the design of educational technologies. 

To account for this, we draw on "social shaping of technology" studies from a critical perspective, borrowing the "script" metaphor developed by Akrich and Latour (1992). Applied to digital inequalities in education, the design and use of educational technologies constitute one and the same process during which power scripts are progressively forged and stabilized by certain actors (industrial, political, IT, educational) at the expense of others, particularly educational actors from disadvantaged environments. Thus, digital inequalities result from the greater or lesser convergence between the educational actors targeted by the design of educational technologies and those who use them.
```

### Parallel Session 13.2 {-}

```{block, type='wp'}
#### The Ripple Effect: Reflecting Upon and Developing an Open Learning Identity Through the Pandemic and Beyond

*Verena Roberts, Thompson Rivers University*

**Keywords:** open advocate, open identity, open educational practices, open learning design 

#### Abstract 

At the beginning of the pandemic, I had just completed my dissertation research which considered the potential of open educational practices in high school contexts. I was excited to go back into K-12 to help support my perceived need for open and online learning during the time of remote access learning. However, I quickly learned that the open learning design intervention (OLDI) principles and findings from my research (Roberts, 2019) had more prospects in Higher Education than in K-12 contexts. As I transitioned through short-term contract positions, I am now a contract Instructional Designer at TRU (Thompson Rivers University) supporting the ZTC Associate Science diploma pathway. My reflective writing and open learning experiences in open pandemic pedagogy (Havemann & Roberts, 2021), open participatory practices including blogging (DeWaard & Roberts, 2021), collaborative picture books (Roberts et. al, 2020), twitter (Brown & Roberts, 2022) and podcasts (Roberts & Neutzling, 2022) and open learning design (Roberts, 2021; Brown et. al, 2021) has inspired my future open research opportunities (Roberts et al., 2022). This talk will tell the story of how the pandemic experiences helped me envision the potential of the Ripple Effect which  encouraged me to balance my open learning designer identity with my professional reality.  Participants will be encouraged to consider their open learning journeys and how to be an open learning advocate in spirit and as a calling. 
```



## Break (1:45 – 2:15) {-}

## Parallel Session 14 (2:15 – 3:45) {-}




### Parallel Session 14.1 – Transitions of Online Learning and Teaching: PSE {-}

```{block, type='secondary'}
#### 2:15-2:45

**Évolution de pratiques pédagogiques inclusives au collégial en contexte pandémique (Research-Oriented)**

*Géraldine Heilporn (Université Laval), Simon Larose (Université Laval), Catherine Beaulieu (Cégep de Saint-Laurent, Montréal, Québec)*
```



```{block, type='secondary'}
#### 2:45-3:45


**Aspirations for post pandemic teaching and learning: Stepping stones for future possibilities**
*Lisa Gedak (Royal Roads University & Kwantlen Polytechnic University)*

**Keywords:** Appreciative Inquiry, Online Learning, Educational Development, Tech-enhanced Practices, COVID-19 Pivot

<!--
[Materials](https://conference.otessa.org/index.php/conference/article/view/34)

-->
#### Abstract

COVID-19 disrupted educational contexts worldwide, providing a possible catalyst for the transformation of teaching and learning. However, without thoughtful reflection and purposeful planning, a post-pandemic return to the status quo seemed likely. The presenters believe that what we focus on determines our perception, and a vision for an ideal future supports purposeful action in that direction.  

This session shares the findings of two distinctive studies. Conducted in unique contexts, both applied an Appreciative Inquiry (AI) approach to explore experiences during the pandemic to identify what is needed for future learning environments. Gedak (2021) examined a British Columbian K-12 school community's experiences during the pandemic and utilized an AI SOAR approach with hopes of positively impacting future district decisions related to education delivery. Waddington (2021) guided a group of post-secondary faculty through an AI-based professional development series to support them to reflect on their initial experience teaching online to identify strengths and opportunities for development and support future adoption of technology and online delivery models. 

The respective findings suggest applicability in other contexts. This session aims to foster dialogue around maximizing the impact of pandemic teaching and learning experiences to meet the needs of diverse learners in a changing world. 


```

### Parallel Session 14.2 – Sustaining Positive Change: K12 Online {-}

```{block, type='secondary'}
#### 2:15-2:45


**Project MIXITÉ: Towards a Numér-ACTIF process of the intervention plan promoting the active participation of the student, his parents, and interprofessional collaborative practices (Practice-Oriented)**

*Audrey Raynault*

#### Abstract 

Research agrees on the fact that the student who actively participates in the process of his plan of intervention (IP) is positively linked to the commitment of the parents in the latter, to the desired learning results, to an increase in the number of high school diplomas in addition to encouraging interprofessional collaboration. Unfortunately, research highlights that practitioners make little use of their collaborative practices and insufficiently promote student agency during the IEP process. The MIXITÉ collaborative research project adopts a collaborative partnership approach in which adults collaborate and maximize their agency and that of the student in the Digital-ACTIVE process of their IP. A collaborative methodology taking place at a distance allowed students, their parents and teachers, the management and the psychoeducator of a school, a patient-partner, social workers and managers of a CIUSSS to co-create two strategies to be implemented. attempt to improve collaborative practices focused on student agency in their IP. This communication presents 1) the process of the IP Digital-ACTIVE to be tested and 2) the planning of intersectoral meetings in order to better understand the roles of each and create cohesion between the actors.
```

```{block, type='secondary'}
#### 2:45-3:45

**Professional Learning and Online Tutoring**

*Michael Canuel (LearnQuebec)*

<!--
[Materials](https://conference.otessa.org/index.php/conference/article/view/143)

-->


**Keywords**: Online tutoring, Professional learning

#### Abstract

There is considerable anecdotal evidence that online tutoring benefits students who participate in these virtual sessions, however, there is also reason to believe that there are numerous advantages for the online tutors who modify, improve, and review their regular classroom practice as a result of their work in the online environment.  While working in this virtual environment, these tutors have the opportunity to discover new tools and resources used in online tutorials which can subsequently be transferred and applied into the face-to-face environment.

```

### Parallel Session 14.3 – Transitions of Online Learning and Teaching: Community {-}

```{block, type='secondary'}
#### 2:15-2:45

**How Digital Technologies Shapes Pedagogical Practices in Virtual Chinese Language Classroom (Research-Oriented)**

*Yina Liu (University of Alberta), Jing Jin (University of Alberta)*

**Keywords:** language teaching, virtual classroom, multiliteracies, digital literacies

#### Abstract 

This presentation focuses on teaching practices of two Chinese language teachers who are also doctoral literacy researchers in virtual Chinese language classrooms during COVID-19. Through a self-study, they conducted an autobiographical narrative inquiry to explore and reflect how digital technology changes their pedagogical practices in early elementary level Chinese language classes. Drawing on Multiliteracies and the notion of new literacies, they look at the multiple literacies embedded in their teaching in the digital space. This paper will shed light on pedagogical practices in Chinese complementary schools in Canada, especially for the post pandemic era.
```

```{block, type='secondary'}
#### 2:45-3:45

**Indigenizing Internationalization and Internationalizing Indigenization: Insights from a Virtual Study Abroad to Ireland, Jamaica, and Aotearoa/New Zealand (Research-Oriented)**

*Michael Cottrell, Kristine Dreaver-Charles (University of Saskatchewan)*

<!--
[Materials](https://conference.otessa.org/index.php/conference/article/view/135)

-->
**Keywords:** Internationalization, Indigenization, Higher Education teaching and learning, Study Abroad, Epistemological third spaces, Decolonizing curriculum

#### Abstract

This proposal aligns with the themes “The Transitions of Online Learning and Teaching” and “Sustaining Positive Change” and reports on the work of a faculty member and an instructional designer from the University of Saskatchewan, where Indigenization and internationalization are leading institutional priorities. We consider possibilities for greater collaboration between these disciplinary and programmatic imperatives for mutual benefit which the shift to virtual learning during the pandemic enabled. We explore the capacity of Virtual Study Abroad course design to synthesize Indigenous and Western pedagogies and methodologies to conceive innovative curriculum consistent with the negotiation of epistemological third spaces through the design of a Virtual Study Abroad course focusing on educational systems in Ireland, Jamaica and New Zealand. Themes emerging from the data include the capacity of virtual learning to enhance the democratization of knowledge and the potential of participatory pedagogies and innovative assessment approaches to decolonize curriculum. Ultimately, we hope that this work will inform new institutional models, whereby Indigenization strategies serve to decolonize internationalization programs and Indigenization efforts are advanced through innovative programming emanating from internationalization imperatives and initiatives. Such a reconceptualization holds the promise of mobilizing Higher Education in the service of social justice and the ‘global good’.


```
### Parallel Session 14.4 – Sustaining Positive Change: Open {-}

```{block, type='secondary'}
#### Provocations and Perspectives: A Work in Progress Learning Design Framework (Practice-Oriented)

*Michael Paskevicius (University of Victoria), Michelle Harrison (Thompson Rivers University), and Irwin DeVries (Royal Roads University)*

<!--
[Materials](https://conference.otessa.org/index.php/conference/article/view/100)

-->

**Keywords**: learning design, open pedagogy, Critical Pedagogy

#### Abstract

In this presentation we provide an update on the development of an experimental variation on the open textbook concept. Originally introduced as an “untextbook” in its early stages, as a customized WordPress site we are now calling it an open digital learning resource. Both scholars and graduate students have been invited to contribute as well as participate in further developing the concept through the submission of provocations. With a focus on learning design, the resulting digital publication is designed in a manner to permit an ongoing evolution, extension and reframing of the original content in learning environments. In response to the provocations, students have been invited, through a series of prompts, to engage with this resource as part of their coursework in a process of ongoing co-creation in a manner consistent with open licensing and pedagogy. In particular it is designed to encourage student responses from critical perspectives including issues, lenses, role perspectives, settings. While the focus of this text is learning design, we envision that the model can be adapted to any other field of inquiry where knowledge is continually evolving or problematized and there is a desire to invite and incorporate alternative perspectives in the educational setting.

```

```{block, type='secondary'}
#### Open Learning Design: Principles & Practices (Practice-Oriented)

*Verena Roberts (University of Calgary & Thompson Rivers University), Leo Havemann (University College London), Helen Dewaard (Lakehead University & University of British Columbia)*

<!--
[Materials](https://conference.otessa.org/index.php/conference/article/view/102)

-->

**Keywords**: open learning design, open educational practices, learning design

#### Abstract

This presentation will consider principles of open learning design, as explored in our forthcoming book chapter which considers the position of open learning designers as ‘Thirdspace professionals’, and highlights our lens as open advocates, open researchers as well as learning designers within higher education (HE) contexts. An intentional, reflective, and open learning design can provide the impetus for a “rethink and redesign” (Ladson-Billings, 2021, p. 73) of teaching and learning environments and curricula.
```

```{block, type='secondary'}
#### How faculty perceptions of and experiences with open access and predatory publications impact teaching and learning (Research-Oriented)

*Richard Hayman (Mount Royal University)*

<!--
[Materials](https://conference.otessa.org/index.php/conference/article/view/107)

-->
**Keywords:** Open access, Scholarly communications, Academic publishing, Teaching and learning

#### Abstract

This presentation presents the results of a research study examining scholars’ awareness and attitudes toward open access (OA) and predatory publishing at a teaching-focused, undergraduate-only university. These faculty (n=154) responded to closed- and open-ended survey questions about their experiences and knowledge using and identifying both quality open access OA and predatory publishing resources as part of their research, teaching, and assessment practices. The results show that while generally supportive of OA, faculty continue to misunderstand OA and are unlikely to use OA resources in their teaching or research. Worse, many did not express strong confidence in their ability to identify and predatory publishers nor to explain predatory publishing to students. Ultimately, scholars may be ill-equipped to teach students and early researchers about open access and predatory publishing practices. This session will primarily highlight the study results focused on the teaching and learning impacts, and seek to address some implications for how new researchers are to gain the essential skills and knowledge needed to navigate the academic publishing landscape.


```

```{block, type='secondary'}
#### Conestoga OER Teaching Case Journal: Creating a peer-reviewed, openly licensed, and accessible teaching case journal at Conestoga College (Practice-Oriented)

*Kevin McDermott, Jane Gravill, Fatih Yegal, Kimberlee Carter (Conestoga College)*

<!--
[Materials](https://conference.otessa.org/index.php/conference/article/view/109)

-->

**Keywords**: OER, Teaching Case Journal, Case Writing, Openly licensed business cases

#### Abstract

Conestoga College is a student-centric community college that services a diverse population of students from a variety of socio-economic backgrounds in south-western Ontario, Canada. To ensure equality for students with less financial means by keeping course material costs low, a group of faculty and administrative staff have created an initiative to encourage faculty members to create quality, OER pedagogical business cases for use in courses. This multi-faceted case writing, and publishing initiative includes three operational pillars: 1) case workshops to help faculty members develop their case writing skills; 2) case roundtable discussions to encourage collaboration and feedback on in-development cases, and; 3) the Conestoga OER Teaching Case Journal, a peer-reviewed, open and accessible, teaching case journal, targeting the submission of cases from a variety of business disciplines. In this session, we will discuss our initial findings related to the efficacy of this initiative and will solicit feedback and collaboration from colleagues.

```

### Parallel Session 14.5 – Wildcard: Open {-}

#### 2:15-2:45: *Wildcard: 10-min ALT Format* {-}

```{block, type='secondary'}


#### Fostering Resiliency in Online Learners: A Blended Test Anxiety Intervention

*Jacqueline Yu*

**Keywords:** test anxiety, online learning, K-12 schools

#### Abstract 

Due to the COVID-19 pandemic, many students are facing potential learning gaps due to periods of emergency teaching, and they lack practice with regulating exam stress. In connection, test anxiety concerns remain a pressing issue in schools. In Alberta, students were initially scheduled to write provincially mandated diploma examinations during the 2021-2 school year; January exams were cancelled, but a decision has not yet been made about upcoming administrations (Government of Alberta, 2021). Although various forms of e-proctoring have garnered interest, research has yet to determine whether such conditions help prepare students for in-person testing or if they foster greater anxiety (Eaton & Turner, 2020). Developed for an online K-12 school, this presentation will highlight a blended test anxiety resource intended to help grade 12 students face in-person standardized testing with confidence. For its asynchronous component, students receive access to web-based content based on the key components of Putwain et al.'s (2014) Strategies to Tackle Exam Pressure and Stress (STEPS). On in-person exam days, students will also receive access to regulatory tools through calming kits.
```

```{block, type='secondary'}
#### The Liberated Learner: How to Learn with Style

*Terry Greene (Trent University), Giulia Forsythe (Brock University)*

<!--
[Materials](https://conference.otessa.org/index.php/conference/article/view/106)

-->

**Keywords**: education, post-secondary, online learning, study skills, collaboration, learning technology, open education, OER

#### Abstract

The Liberated Learner, funded by the eCampusOntario Virtual Learning Strategy, is an inter-institutional collaboration that brings together student co-designers and elearning professionals. This open resource consists of four modules that mirror the Ontario Extend for Educators modules (Lopes & Porter, 2018), but are customised to the learner context. These modules are Learner (learning strategies), Technologist (digital fluency skills), Collaborator (communication, group work, community member), & Navigator (curating, fact checking, other scholarly skills). The goal is to provide learners a similar opportunity to gain confidence and independence in their post-secondary experience online.

Recognizing that most issues post-secondary students face are complex and ill-structured (Cormier, 2021), the design and development of the Liberated Learner open modules were primarily student-led. During a week-long design sprint, 120 students generated 99 wicked problems. This collection of personal stories document students’ real life post-secondary challenges. These stories then informed the content of the 4 modules as they were developed together with student co-designers from each institution. They also provided a pathway into the Liberated Leaner modular support at multiple levels of experience (beginner, intermediate, advanced). Each module also consists of a student created Beats to Study to intro to help learners get into the learning groove.
```

```{block, type='secondary'}
#### The role of inquiry-based information literacy curriculum design in fostering self-efficacy in the digital learning environment

*Marta Samokishyn (Saint Paul University)*

<!--
[Materials](https://conference.otessa.org/index.php/conference/article/view/139)

-->

**Keywords**: Information literacy, Online learning, Self-efficacy

#### Abstract

Students’ motivation and engagement have been a subject of concern in online learning, especially over the last two years (Means & Neisler, 2021). The inquiry-based approach in information literacy education has shown to increase students’ self-efficacy and sense of agency (Leat, 2017), promote engagement and cognitive presence, as essential building blocks for the development of students’ critical thinking skills. This presentation will discuss the development of an inquiry-based IL curriculum for the credit-bearing collaborative 1st-year undergraduate course in Social Sciences and Humanities. The presenter will discuss how inquiry-based learning can facilitate self-efficacy in the digital learning environments, as we move forward.

```

```{block, type='secondary'}
#### 2:45-3:45

**Learning In the Open: The Journey of Creating and Implementing Open Web-Based Portfolio Templates (Practice-Oriented)**

*Melanie Laurie (Fraser Health), Jamie Drozda (Thompson Rivers University)*

**Keywords**: ePortfolio, digital competencies, open

#### Abstract 

The authors will discuss the process of building WordPress sites as ePortfolio templates for faculty and students to adopt in their coursework and as digital spaces to showcase their learning. Eportfolios themselves are not a novel innovation of the pandemic, however, they were used in creative ways to replace field work, practicums, and art galleries. The authors saw a desperate need for faculty and students to be supported with open source portfolio technologies. In addition, many faculty and students had little technical expertise or funds to develop a website or ePortfolio, which is why the authors developed a series of clonable WordPress ePortfolio template sites. Initially, their aim was to support students by creating open ePortfolio templates with a simple structure and step-by-step instructions for website building, artifact curation and reflection. As they implemented the ePortfolio templates into their respective workplaces, they humbly realized how large some of the technical and pedagogical gaps in understanding can be and so an iterative approach was taken to refine the authors’ instructional process, and the templates themselves were revamped to be more user friendly for the beginner content creator.
```


## Break (3:45 – 4:00) {-}

## Social Session (4:00 – 4:30) {-}

```{block, type='gh'}
#### Dr Jones (DJ)

*Beats*
```

## Parallel Session 15 (4:30 – 5:30) {-}

### Parallel Session 15.1 – Sustaining Positive Change: PSE Online Teacher Education {-}

```{block, type='secondary'}
#### Practicum During the Pandemic: Zooming In (Practice-Oriented) 

*Christine Ho Younghusband (University of Northern British Columbia)*

**Keywords:** practicum, teacher education, remote learning, video conferencing, program evaluation, policy

#### Abstract 

Universities in British Columbia pivoted to remote online learning in March 2020 and remained online in the upcoming school year. Teacher Education Programs also pivoted to remote online learning, with exception to practicum. Teacher candidates returned K-12 schools for practicum as of the Fall 2020 term while coursework at universities remained online. Teacher candidates were placed in their home communities, if possible, for practicum. At one university, some teacher candidates were formally observed and supported by the practicum mentor remotely due to limited staffing, location of placement, and COVID safety protocols. Formal observations and pre- and post-conferences with the Teacher Candidate were held on Zoom. This session will discuss the pros and cons of remote observations for practicum, privacy and policy issues, and recommendations regarding the use of video conferencing applications for formal observations.
```

```{block, type='secondary'}
#### Equipping Pre-Service Teacher Candidates for a Post-Pandemic Reality: Building e-Pedagogy Skills and Connecting Theory to Praxis (Practice-Oriented)

*Karen Roeck (Heritage Christian Online School), Nina Pak Lui (Trinity Western University)*

**Keywords:** educational technology, e-pedagogy, teacher education, practicum

#### Abstract 

This practice-oriented session addresses two identified gaps: (a) the absence of e-pedagogy skill development in teacher education programs (e.g., strategies specific to online teaching) (Serdyukov, 2015); and (b) a lack of ongoing opportunities for teacher education students to apply content and pedagogical knowledge in real classrooms guided by mentor teachers. This session is relevant to the conference themes of “The Transitions of Online Learning and Teaching” and “Sustaining Positive Change.” Our work was guided by three inquiry questions:

1. What skills do 21st century teachers need to create inclusive, equitable, human-centred learning environments and serve students in a variety of modalities?
2. Where should pre-service teachers complete their field experience to best prepare them for all teaching and learning opportunities in British Columbia (BC)?
3. What are the impacts on professional learning of pre-service teachers when they have field experiences with online educators?
```

```{block, type='secondary'}

#### Building Open Education Resources with Teacher Candidates – Reflections from the Field

*Natalie Currie Patterson, Emma Facca, Victoria Crocco, Brock University*

**Keywords:** open pedagogy, OER, teacher education, ungrading, collaborative grading, open educational resources

#### Abstract

This paper will share reflections on the ideation, process, and outcome of cultivating an open pedagogical practice and the creation of a collaborative Open Education Resource (OER) with students in a pre-service education course. The OER co-created by the class is the outcome of a major class assignment, the planning of a course from the Canadian and World Studies Ontario curriculum, grades 7 through 12. The creation of this OER is embedded in a broader shift in course design to open pedagogical practices and collaborative grading strategies.  

The course instructor alongside student contributors reflect on the ways the enactment of open pedagogical practice, a privileging of learning processes and collaboration impacted their teaching and learning environment. Teacher candidates will share insight into their experiences with modelled open pedagogy, opportunities for critical reflection, and multi-directional collaboration. For teacher candidates these experiences encouraged contemplation on the complexities of enacting open practice and the ways these approaches might be enacted in the K-12 field while also offering insight on various challenges involved in such practice. For the instructor, the shifts in course design brought also brought benefits, opportunities, and challenges. The experience highlighted the complexity of open pedagogy in practice in post-secondary education.  
```

### Parallel Session 15.2 – Sustaining Positive Change: PSE Graduate Ed {-}

```{block, type='secondary'}
#### Graduate Supervision Webinar Series: Open, Online, and Transdisciplinary Faculty Development (Research-Oriented)

*Michele Jacobsen, PhD, Werklund School of Education, University of Calgary  
Hawazen Alharbi, PhD, King Abdulaziz University, Saudi Arabia, hsalharbe@kau.edu.sa  
Shauna Reckseidler-Zenteno, PhD, Athabasca University, shaunaz@athabascau.ca  
Shawn Fraser, PhD, Athabasca University, shawnf@athabascau.ca  
Sonja Johnston, PhD student, Werklund School of Education, University of Calgary, sonja.johnston@ucalgary.ca*  

**Keywords:** webinars, MOOCs, online community of practice, graduate supervision, faculty development

#### Abstract 

The Quality Graduate Supervision (QGS) MOOC engages academics from across disciplines at different universities in sharing and examining effective graduate supervision practice. Our MOOC combines synchronous and asynchronous learning activities and rich resources on various topics and issues in graduate education and supervisory relationships. Academics join an online community of practice (OCoP) to discuss and explore transdisciplinary strategies for effective graduate supervision and mentoring. The focus of this paper is the QGS MOOC Webinar series that brings faculty and expert panelists together in real time to discuss and explore complex issues in graduate supervision.  The Weekly Webinar series invites supervisors into live conversations with peers, course instructors and expert panelists. Faculty attendance was high every week. During a demanding semester, busy faculty regularly showed up to engage in dynamic conversations. The Webinars increased supervisors’ sense of belonging in the OCoP and enhanced the value of the course. Online faculty development offers significant opportunities for democratizing knowledge about graduate supervision. The open and online design of the MOOC and Webinar series increased access to a broad and diverse community of professors and enhanced possibilities for collaboration across institutions that leveraged expertise and capacity in graduate supervision. 
```

### Parallel Session 15.3 - Wildcard: PSE Online {-}

```{block, type='secondary'}
#### From Crime Scene to the Laboratory: Travel CSI style!

*Sanela Martic, Stephanie Ferguson, James Bailey (Trent University)*

**Keywords:** chemistry, toxicology, forensic science, laboratory, podcasts, videos, slides

#### Abstract 

How would you like to experience a day in a life of a Forensic Toxicologist?  This session will describe the design and development of digital content MODULES and virtual labs to introduce toxicological concepts for their analysis, reporting and interpretation in forensic context. The MODULE I will focus on 7 classes of toxic chemicals, and MODULE II will overview current testing technologies in forensic science field. Using the interactive H5P Course Presentations which will include slide decks, and podcasts, the intricate link between chemical toxicity and testing will be demonstrated in relation to crime scenes and cases. The virtual laboratory component will showcase 5 independent experiments targeting specific chemical, and how current instrumentation is used for their analysis, reporting and interpretation. Lab videos alongside worksheets/datasets will provide an opportunity to partake in a forensic toxicology lab setting. The assessments by forensic toxicology students will be discussed as well. This project was funded through the VLS eOntario program and Ontario Government.
```

### Parallel Session 15.4 – Transitions of Online Learning and Teaching – Open {-}


```{block, type='secondary'}
#### Lessons from the Pandemic: How did a terrible online course make a better textbook? (Practice-Oriented)

*Rebekah Bennetch (University of Saskatchewan), Zach Keesey*

**Keywords:** open educational resource, technical communication, grammar, writing, report writing, public speaking, H5P, case studies

#### Abstract 

Like all educators in 2020, we struggled with the transition to online learning. The sudden shift to a remote, asynchronous learning environment was a challenge we often had to meet; however, from that challenge came an opportunity. 

Instead of staying stuck in our remote course mistakes, we used them to create something new: an attractive, accessible, and inclusive Open Education Resource (OER) textbook for our technical communication course. Our presentation will walk through our process of taking a lackluster online course and turning it into an effective textbook.   

Additionally, we will share tips and strategies for designing H5P activities and case studies that stimulate higher order thinking, discuss best practices for making an online text accessible and inclusive, and explain how we sorted through an unlimited amount of existing OER texts to create our own. 
```

```{block, type='secondary'}
#### Show Me Your Crystal Ball: An Environmental Scan for Usefulness (Practice-Oriented)

*[Jenni Hayman](http://orcid.org/0000-0001-6410-7235) (Cambrian College)*

<!--
[Materials](https://conference.otessa.org/index.php/conference/article/view/131)

-->

**Keywords**: post-pandemic teaching, multi-modal learning, literature review

#### Abstract

In the past year, there have been a lot of articles. A lot of shared ideas and many strategies, tips, and tricks focused on how to manage the continuity of post-secondary teaching and learning during a relentless global pandemic. It’s my sense that we’re not anywhere near the end of this pandemic, despite what some in positions of political leadership might wish or pretend. There is more uncertainty to come, possibly significant uncertainty as colleges and universities begin to pick up the pieces of their shattered perceptions and begin the difficult work of personal and institutional recovery.

It is hard to imagine anyone in Canadian higher education (learners, faculty, staff, administrators, employer partners) that has not been negatively impacted by COVID-19 decisions, changes in practice, and shifting priorities. It has been a messy two-plus years of chaos. There has been no lack of advice–and perhaps now might be a good time to sort through some of the recommendations, check the accuracy and usefulness of predictions and strategies, and begin a collection of works that support collective success for post-secondary futures. The purpose of this session is to share some useful works and collect and share new favourites from participants.

```

```{block, type='secondary'}
#### Opening a Seminal Work for the Next Century (Practice-Oriented)

*[Kristine Dreaver-Charles](https://orcid.org/0000-0003-2550-163X), [Monique Mayer](https://orcid.org/0000-0003-3414-3918) (University of Saskatchewan)*

<!--
[Materials](https://conference.otessa.org/index.php/conference/article/view/97)

-->

**Keywords**: Open textbooks, Open education resources (OER), H5P, Equitable access, Catalysts of open

#### Abstract

This contribution is situated at the University of Saskatchewan, where Open Education Resources have been supported since 2014-2015. During the pandemic we began the work of translating The Lymphatic System of the Dog, by Dr. Hermann Baum into English. Originally published in 1918, Dr Baum’s book has been transitioned into Pressbooks, with the addition of ancillary resources. Balancing the legacy of Dr. Baum’s research with our own innovations in assessment and design engages new generations of learners and practitioners. The benefits for faculty and graduate students in designing and publishing openly must also be acknowledged. Locally designed and produced open education resources created with and by our university community is of significance to the academy. The use of open textbooks in university classes establishes a discourse and refinement of knowledge ensuring quality resources are designed and shared.

```


### Parallel Session 15.5 {-}

```{block, type='secondary'}
#### 4:30-5:00 – Sustaining Positive Change - PSE

**Investigating the Conversational Framework as a design approach (Research-Oriented)**

*Maryam Shirdel Pour, Michael Paskevicius (University of Victoria)*

<!--
[Materials](https://conference.otessa.org/index.php/conference/article/view/146)

-->
**Keywords**: Conversational Framework, Open Educational Resources, Open educational practices, students’ engagement, knowledge creation.

#### Abstract

The “Conversational Framework”, which represents a learning design framework for teaching and learning processes, could be used as a guide for integrating Open Educational Resources (OER) into education. With the growing tendency toward open and adaptable pedagogy, OER have achieved popularity as a method for supporting students’ access and enabling contributions to knowledge. These resources provide students with the possibility to play an active role in creating knowledge. However, the development of an effective environment to foster the process of learning can benefit from being grounded in a theoretical framework. The purpose of this paper is to explore the application of the “Conversational Framework” (Laurillard 2002, 2012) in designing effective educational experiences and specifically how OER may support students’ learning and engagement. Moreover, it will be discussed how this framework can help teachers consider how to design open learning experiences.


```

```{block, type='secondary'}
#### 5:00-5:30 – Addressing the New Inequities - PSE

**Defining Diversity in the Development of a Health Education Media Library (Practice-Oriented)**

*Danielle Dilkes (University of Western Ontario)*

<!--
[Materials](https://conference.otessa.org/index.php/conference/article/view/111)

-->

**Keywords**: open education, media, representation, cataloguing, participatory design, diversity, diversity theatre

#### Abstract

This interactive session is a reflection on the complexity of diversity and representation in the design of educational materials using the example of the development of the Health Education Media Library, a project funded by the 2021 eCampus Virtual Learning Strategy. This project was a response to the challenges of finding high-quality, diverse and inclusive media while creating health education content. The proposed solution was a community-sourced library of images, video and audio that would be made widely available for health educators. As the project evolved, however, this simplistic approach revealed the complexity of diversity work in higher education, starting with the not simple task of defining diversity, how that definition can codify identity, and the implications of that definition including some groups and excluding others. This session will provide an opportunity to reflect on some of the questions and considerations that were raised through the initial phase of the Health Education Media Library project, linking them to broader diversity discourse in higher education, curricular design, and media cataloguing. The session will reflect on the importance of how we approach this work and who is included, concluding with a reimagining of the participatory design of the project. 

```



## Break( 5:30 – 6:00) {-}




## \#tresdancing - Invited Speakers (6:00 – 6:45) {-}

```{block, type='wp'}
#### Short Film Screening and Q&A with Filmmakers

*sava saheli singh, University of Ottawa (co-producer)*  
*Tim Maughan (script writer)*  
*Hingman Leung (director)*  
*Lesley Marshall (co-producer)*  

**Keywords:** ed tech, surveillance, AR, acab 

#### Abstract 

The sudden shift from in-person to online classes due to COVID 19 has led to increasingly invasive surveillance technologies in education, including the use of problematic online proctoring software purportedly aimed at addressing academic integrity. 

#tresdancing, the fourth film in the Screening Surveillance series (www.screeningsurveillance.com), speculates on the effects of escalating surveillance and control through educational technology. In this near future fiction narrative, a young person has little choice as they are forced to ramp up their engagement with a new, experimental technology in order to make up for a failing grade.
```

## Closing Comments - Conference Co-Chairs / Introducing Workshops & Unconference (6:45 – 6:55) {-}


## Discussion/Networking Pods 6:55 – ♾️ {-}




